// Generated by CoffeeScript 1.6.3
var Slack, domain, should, webhookToken;

should = require("should");

Slack = require("../index");

domain = "slack-node";

webhookToken = "ROHgstANbsFAUA5dHHI5JONu";

describe('slack webhook part', function() {
  var slack;
  slack = new Slack(webhookToken, domain);
  it(',should send a correct response', function(done) {
    slack.should.be.an.Object;
    return done();
  });
  return it(',should send a correct response', function(done) {
    return slack.post({
      channel: "#general",
      username: "webhookbot",
      text: "This is posted to #general and comes from a bot named webhookbot."
    }, function(err, response) {
      response.should.be.ok.and.a.String;
      return done();
    });
  });
});
